markdown: redcarpet
pygments: true
permalink: /blog/:year/:month/:day/:title
include: ['.well-known']
rdiscount:
  extensions: [smart]
title : joncanady (dot com)
production_url : http://joncanady.com
description: "A site."
author :
  name : Jon Canady
  github : joncanady
  twitter : joncanady
