markdown: redcarpet2
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]
pygments: true
permalink: /blog/:year/:month/:day/:title
auto: true
rdiscount:
  extensions: [smart]
title : joncanady (dot com)
production_url : http://joncanady.com
description: "A site."
author :
  name : Jon Canady
  github : joncanady
  twitter : joncanady
